[general]
serverName = WIN10-01
pass4SymmKey = <redacted>

[sslConfig]
sslPassword = <redacted>

[lmpool:auto_generated_pool_forwarder]
description = auto_generated_pool_forwarder
peers = *
quota = MAX
stack_id = forwarder

[lmpool:auto_generated_pool_free]
description = auto_generated_pool_free
peers = *
quota = MAX
stack_id = free
